---
- hosts: localhost
  vars:
    ocp_user: "{{ ocp_user }}"
    ocp_pass: "{{ ocp_pass }}"
    ocp_api_url: "https://api.cluster-1547.sandbox1757.opentlc.com:6443"
  module_defaults:
    group/k8s:
      host: "{{ ocp_api_url }}"
      validate_certs: false
  roles:
    - monitoring
    - splunk
